# Generated by Django 4.2.1 on 2024-03-13 08:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_points', models.IntegerField(default=0)),
                ('t2_points', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2024, 3, 13, 8, 37, 56, 397695, tzinfo=datetime.timezone.utc))),
                ('t1', models.ManyToManyField(blank=True, related_name='team_one', to=settings.AUTH_USER_MODEL)),
                ('t2', models.ManyToManyField(blank=True, related_name='team_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(blank=True, related_name='matches', to='matches.matches')),
            ],
        ),
    ]
