# Generated by Django 4.2.1 on 2024-03-22 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matches_options_alter_matchhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('matches', models.ManyToManyField(blank=True, to='matches.matches')),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='matches.tournaments'),
        ),
    ]
