# Generated by Django 4.2.1 on 2024-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_rename_username_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
