# Generated by Django 4.2.1 on 2024-03-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'verbose_name': 'Match History', 'verbose_name_plural': 'Match Histories'},
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='total_matches',
            field=models.IntegerField(default=0),
        ),
    ]
