# Generated by Django 4.2.1 on 2024-03-22 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blocklist', models.ManyToManyField(blank=True, related_name='block', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Block List',
                'verbose_name_plural': 'Block List',
            },
        ),
    ]
